### ISSUE TITLE
Ideas - Summer (pending)

### ISSUE THREAD

**Issue by SummerPapaya** [shufangOrg/shufang.org#35]
To be continued …

**PHASE 1**

**Website Structure**

- [ ] Audio player - main page / individual pages for each series or episodes

- [ ] About Us - organization / each member

- [ ] Archives - audio / texts

**PHASE 2**

**Community Interaction**

- [ ] Blog / WeChat posts - linking to the website Shufang 2.0

- [ ] Online Book Club 

- [ ] Shufang reunion - launching of Shufang 2.0
